import logging
import os
import sys
from unittest.mock import MagicMock, patch

# Add project root to path
sys.path.append(os.getcwd())

from src.config_manager import ConfigManager
from src.controllers.transcription_ctrl import TranscriptionController
from src.core.history_mgr import history_mgr
from src.core.state import state

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def test_metadata_automation():
    logger.info("Starting Metadata Automation Verification Test...")

    # Setup mocks
    mock_config = MagicMock(spec=ConfigManager)
    mock_config.get_whisper_model.return_value = "base"
    mock_config.get_force_gpu.return_value = False
    mock_config.get_last_model.return_value = "gemini-1.5-flash"
    mock_config.get_active_provider.return_value = "gemini"
    mock_config.get_provider_config.return_value = {"api_key": "test_key"}

    mock_transcriber = MagicMock()

    ctrl = TranscriptionController(mock_config, mock_transcriber)

    # 1. Test Default Project Name "その他"
    state.set("project_name", "")  # Empty
    state.set("category", "")  # Empty

    logger.info("Case 1: Empty project name should default to 'その他'")

    # Mocking history_mgr.add_meeting to see what's being passed
    with patch.object(history_mgr, "add_meeting", return_value=999) as mock_add:
        with patch("src.live_processor.LiveTranscriptionManager"), patch("src.recorder.visual_recorder.visual_recorder.start"):
            ctrl.start_live_recording("base", "microphone")

            args, kwargs = mock_add.call_args
            assert kwargs["project_name"] == "その他", f"Expected 'その他', got {kwargs['project_name']}"
            logger.info("✅ Case 1 Passed: Project name defaulted to 'その他'")

    # 2. Test Automated Category Generation
    logger.info("Case 2: Empty category should be auto-generated by LLM")

    # Setup state for stop
    state.set("current_meeting_id", 999)
    state.set("category", "")  # Still empty

    mock_live_mgr = MagicMock()
    mock_live_mgr.stop.return_value = "これはAI技術に関する会議のテストテキストです。"
    mock_live_mgr.mp3_path = "test.mp3"
    ctrl.live_mgr = mock_live_mgr

    # Mock LLM Client
    mock_llm_client = MagicMock()
    mock_llm_client.extract_category.return_value = "AI技術, テスト"

    with (
        patch("src.llm.factory.LLMFactory.create_client", return_value=mock_llm_client),
        patch.object(history_mgr, "update_meeting") as mock_update,
        patch("src.recorder.visual_recorder.visual_recorder.stop"),
    ):
        # We need to wait for the thread to finish or mock threading.Thread
        with patch("threading.Thread") as mock_thread:
            ctrl.stop_live_recording()

            # Manually trigger the worker if we mock Thread
            target = mock_thread.call_args[1]["target"]
            target()  # Execute _stop_worker

            args, kwargs = mock_update.call_args
            assert kwargs["category"] == "AI技術, テスト", f"Expected 'AI技術, テスト', got {kwargs['category']}"
            assert state.get("category") == "AI技術, テスト"
            logger.info("✅ Case 2 Passed: Category was auto-generated and saved")

    logger.info("All Metadata Automation Checks Passed!")


if __name__ == "__main__":
    try:
        test_metadata_automation()
    except Exception as e:
        logger.error(f"Test Failed: {e}")
        import traceback

        traceback.print_exc()
        sys.exit(1)
